feat: first version of user point system.
SJTU-jCourse/jcourse_go pull request #10
Opened 2024-11-06 15:53 UTC by Ayanami1314

just for test

2024-11-06 16:08 UTC, dujiajun requested changes

2024-11-06 16:08 UTC, dujiajun commented on router.go
> +	middleware.InitEvent(r)
这是啥

2024-11-06 16:08 UTC, dujiajun commented on router.go
> +	api.POST("test", handler.TestAddCreditHandler)
写完了记得删除，或者仅在debug模式使用

2024-11-06 16:08 UTC, dujiajun commented on handler/auth.go
> +
单独开一个接口。另外一个pr已经在处理测试环境中的注册问题了。

2024-11-06 16:08 UTC, dujiajun commented on service/user.go
> +	}
service 层里不要出现 gorm.DB

2024-11-06 16:08 UTC, dujiajun commented on service/user.go
> +	}
如果它是一个事务，应该是repository层关心的

2024-11-06 16:08 UTC, dujiajun commented on service/user.go
> +	// 给传承等开放的兑换积分接口
从现行功能来讲，只是开了查询接口，兑换积分不会让选课社区的积分减少。传承自己维护了已兑换的积分数量。

2024-11-06 16:08 UTC, dujiajun commented on service/user.go
> +	}
同上

2024-11-06 16:08 UTC, dujiajun commented on service/user.go
> +}
正好接 site settings 吧。

2024-11-06 16:08 UTC, dujiajun commented on util/timeutil.go
> +const layout = "2006-01-02 15:04:05" // Go的参考时间
前面出现了字面量，引用到这个常量吧

2024-11-08 06:36 UTC, Ayanami1314 commented on model/dto/user.go
> +	EndTime   string `json:"end_time" form:"end_time"`
https://segmentfault.com/a/1190000022264001
gin里面直接用time.Time似乎会有一些问题，限制死了前端传入的字符串的形式是2006-01-02T15:04:05Z07:00
这样，不能是yyyy-mm-dd hh:mm:ss或者其他的形式
还有就是我觉得字符串为空表示不限制比较自然？

2024-11-08 09:18 UTC, Ayanami1314 commented on service/user.go
> +	}
ok, 把这部分逻辑下放到了repository
我想问一下如果事务失败了，重试的部分应该放在上层自行实现，还是用一个站点设置规定重试次数之类？
需要包装成一个util函数吗

2024-11-08 09:20 UTC, Ayanami1314 commented on service/user.go
> +	// 给传承等开放的兑换积分接口
那我们这里需要记录这个兑换信息吗？还是全部交给传承，这里只留一个和传承通信的待实现的东西

2024-11-08 10:44 UTC, Ayanami1314 commented on util/timeutil.go
> +const layout = "2006-01-02 15:04:05" // Go的参考时间
什么字面量？

2024-11-08 10:44 UTC, Ayanami1314 commented on service/user.go
> +}
是改成从site sitting里面读取这个rate吗

2024-11-08 10:45 UTC, Ayanami1314 commented on middleware/auth.go
> +}
ok

2024-11-08 10:45 UTC, Ayanami1314 commented on model/po/user.go
> +)
ok, 放到model里面了

2024-11-08 10:46 UTC, Ayanami1314 commented on router.go
> +	api.POST("test", handler.TestAddCreditHandler)
ok

2024-11-08 12:09 UTC, dujiajun commented on service/user.go
> +	// 给传承等开放的兑换积分接口
不记录，展示用户有多少积分就行了

2024-11-08 12:09 UTC, dujiajun commented on service/user.go
> +	// 给传承等开放的兑换积分接口
和原来的接口保持一致

2024-11-08 12:10 UTC, dujiajun commented on service/user.go
> +}
对，可以设一个默认值。但是如果设置了的话，以数据库里实时值为准。

2024-11-08 12:11 UTC, dujiajun commented on service/user.go
> +	}
事务失败了就返回错误，给用户展示错误信息。不用重试。

2024-11-08 12:12 UTC, dujiajun commented
再 merge main 解下冲突，以及过下ci

2024-11-08 12:18 UTC, dujiajun commented on model/dto/user.go
> +	EndTime   string `json:"end_time" form:"end_time"`
dto 可以就用 int64 吧。handler 层转一下格式。我对url里处理字符串中的空格等特殊符号会感觉不舒服。

2024-11-08 12:18 UTC, dujiajun commented on service/user.go
> +	description := fmt.Sprintf("用户%d转账给用户%d %d分", senderID, receiverID, value)
这个字面量抽出成常量

2024-11-08 12:18 UTC, dujiajun commented on util/timeutil.go
> +const layout = "2006-01-02 15:04:05" // Go的参考时间
我记得你前面有个地方也出现了 2006-01-02 15:04:05。

2024-11-08 14:18 UTC, Ayanami1314 commented on service/user.go
> +	// 给传承等开放的兑换积分接口
我把这个接口删了，我看原来的代码传承就是重定向到传承那边，后端没有相关接口来着（只有查询分数）

2024-11-08 14:18 UTC, Ayanami1314 commented on util/timeutil.go
> +const layout = "2006-01-02 15:04:05" // Go的参考时间
好的，是在converter里面，拿出来放util了

2024-11-08 16:54 UTC, Ayanami1314 commented on handler/user.go
> +	}
uri和json是不行的，之前我调的时候是不能bind上去的
https://github.com/gin-gonic/gin/issues/1824
https://github.com/gin-gonic/gin/issues/2535
其他绕过的方法感觉都更复杂了

开始我是把这两个全放在json的，这样的话感觉router的uri设计会和其他的不统一，但也可以改router

2024-11-08 16:57 UTC, Ayanami1314 commented on handler/user.go
> +	}
是指做到router里面吗？那需要规定一下request的userID参数的位置感觉
统一在request form里面的userID？

2024-11-08 17:10 UTC, Ayanami1314 commented on service/user.go
> +	}
ok, 我改成withpaginate了
dto那边也用嵌入的PaginationFilterForQuery换掉了

2024-11-08 17:13 UTC, Ayanami1314 commented on cmd/import_from_jwc/import_from_jwc.go
> +	}
确实有这一列是空的数据，我在导2024-2025-1的时候发现的
如果这里不return下面teacherInfo[1]会错误

2024-11-09 04:53 UTC, dujiajun commented on handler/user.go
> +	}
对，在router层面指定这些接口的权限

2024-11-09 04:53 UTC, dujiajun commented on handler/user.go
> +	}
用不了就这样吧

2024-11-09 07:10 UTC, Ayanami1314 commented on handler/user.go
> +	}
我把这几个接口都拆开了，分别拆成Admin和非Admin两个接口，然后不同的接口就可以直接用不同的request参数了
感觉之前的那样不是很好做

2024-11-11 14:52 UTC, dujiajun commented on handler/user.go
> +}
感觉没有这个接口的场景。因为流水明细本来字段就少，直接list就行了

2024-11-11 14:52 UTC, dujiajun commented on model/model/user.go
> +}
把这些point的单独放到一个文件里吧

2024-11-11 14:53 UTC, dujiajun commented
其他差不多了，明天可以合了

2024-11-11 15:28 UTC, Ayanami1314 commented on handler/user.go
> +}
那这个接口删掉吗？

2024-11-12 07:54 UTC, dujiajun commented on handler/user.go
> +}
删掉吧

2024-11-12 08:13 UTC, Ayanami1314 commented on handler/user.go
> +}
ok, 删掉了

2024-11-12 14:08 UTC, merged