Docs how to run
SJTU-jCourse/jcourse_go pull request #9
Opened 2024-11-03 15:04 UTC by creeper12356

- 在Debug模式下，注册用户不校验邮箱验证码（随便填即可）
- 在README增加了如何从源代码构建并运行后端的指导
- 将2024-2025-1.csv文件加入版本管理

2024-11-06 15:36 UTC, dujiajun requested changes

2024-11-06 15:36 UTC, dujiajun commented on data/2024-2025-1.csv
这个不要放在代码仓库吧，有很多校内信息

2024-11-06 15:36 UTC, dujiajun commented on service/auth.go
> +	if !util.IsDebug() {
我觉得为debug单独设计一个接口吧，不要在service里插debug判断。

2024-11-07 02:19 UTC, creeper12356 commented
我将csv文件替换为了一个假的dummy文件，以供测试。
同时删除了service/auth.go中判断IsDebug的逻辑，后续再为debug单独设计接口吧。

2024-11-07 09:52 UTC, dujiajun approved these changes

2024-11-07 09:52 UTC, merged